version: '3'

services: 

  app:
    build: 
      context: node
    container_name: app
    entrypoint: sh -c "npm install && dockerize -wait tcp://db:3306 -timeout 20s node index.js"
    restart: always
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db

  db:
    build: 
      context: mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx:
   image: nginx:latest
   container_name: nginx_proxy
   restart: always
   depends_on:
     - app
   volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
   ports:
     - "8080:80"
   networks:
     - node-network

networks: 
  node-network:
    driver: bridge      